// This file was automatically generated by make-pins.py
//
// --af TM4C123GH6P_af.csv
// --board LAUNCHPAD_TM4C123G/pins.csv
// --prefix cc3200_prefix.c

/*
 * This file is part of the Micro Python project, http://micropython.org/
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2013, 2014 Damien P. George
 * Copyright (c) 2015 Daniel Campora
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

// cc3200_prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>
#include <stdint.h>

#include "py/mpconfig.h"
#include "py/obj.h"
//#include "inc/hw_types.h"
//#include "inc/hw_memmap.h"
#include "pins.h"
#include "gpio.h"
#include "pybpin.h"


#define AF(af_name, af_idx, af_fn, af_unit, af_type) \
{ \
    .name = MP_QSTR_ ## af_name, \
    .idx = (af_idx), \
    .fn = PIN_FN_ ## af_fn, \
    .unit = (af_unit), \
    .type = PIN_TYPE_ ## af_fn ## _ ## af_type, \
}


#define PIN(p_pin_name, p_port, p_bit, p_pin_num, p_af_list, p_num_afs) \
{ \
    { &pin_type }, \
    .name           = MP_QSTR_ ## p_pin_name, \
    .port           = PORT_A ## p_port, \
    .af_list        = (p_af_list), \
    .pull           = PIN_TYPE_STD, \
    .bit            = (p_bit), \
    .pin_num        = (p_pin_num), \
    .af             = PIN_MODE_0, \
    .strength       = PIN_STRENGTH_4MA, \
    .mode           = GPIO_DIR_MODE_IN, \
    .num_afs        = (p_num_afs), \
    .value          = 0, \
    .used           = false, \
    .irq_trigger    = 0, \
    .irq_flags      = 0, \
}

// PB6
const pin_af_t pin_PB6_af[] = {
    AF(SSI2_RX         ,    2, SSI     ,    2, RX      ),    // SSI2_RX
};
pin_obj_t pin_PB6  = PIN(PB6   , 1,  64,  0, pin_PB6_af, 1);

// PB7
const pin_af_t pin_PB7_af[] = {
    AF(SSI2_TX         ,    2, SSI     ,    2, TX      ),    // SSI2_TX
};
pin_obj_t pin_PB7  = PIN(PB7   , 1, 128,  3, pin_PB7_af, 1);

// PF4
pin_obj_t pin_PF4  = PIN(PF4   , 1,  16,  4, NULL, 0);

// PE3
pin_obj_t pin_PE3  = PIN(PE3   , 1,   8,  5, NULL, 0);

// PE2
pin_obj_t pin_PE2  = PIN(PE2   , 1,   4,  6, NULL, 0);

// PE1
const pin_af_t pin_PE1_af[] = {
    AF(UART7_TX        ,    1, UART    ,    7, TX      ),    // UART7_TX
};
pin_obj_t pin_PE1  = PIN(PE1   , 1,   2,  7, pin_PE1_af, 1);

// PE0
const pin_af_t pin_PE0_af[] = {
    AF(UART7_RX        ,    1, UART    ,    7, RX      ),    // UART7_RX
};
pin_obj_t pin_PE0  = PIN(PE0   , 1,   1,  8, pin_PE0_af, 1);

// PD7
const pin_af_t pin_PD7_af[] = {
    AF(UART2_TX        ,    1, UART    ,    2, TX      ),    // UART2_TX
};
pin_obj_t pin_PD7  = PIN(PD7   , 1, 128,  9, pin_PD7_af, 1);

// PC7
const pin_af_t pin_PC7_af[] = {
    AF(UART3_TX        ,    1, UART    ,    3, TX      ),    // UART3_TX
};
pin_obj_t pin_PC7  = PIN(PC7   , 1, 128, 12, pin_PC7_af, 1);

// PC6
const pin_af_t pin_PC6_af[] = {
    AF(UART3_RX        ,    1, UART    ,    3, RX      ),    // UART3_RX
};
pin_obj_t pin_PC6  = PIN(PC6   , 1,  64, 13, pin_PC6_af, 1);

// PC5
const pin_af_t pin_PC5_af[] = {
    AF(UART4_TX        ,    1, UART    ,    4, TX      ),    // UART4_TX
    AF(UART1_TX        ,    2, UART    ,    1, TX      ),    // UART1_TX
    AF(UART1_CTS       ,    8, UART    ,    1, CTS     ),    // UART1_CTS
};
pin_obj_t pin_PC5  = PIN(PC5   , 1,  32, 14, pin_PC5_af, 3);

// PC4
const pin_af_t pin_PC4_af[] = {
    AF(UART4_RX        ,    1, UART    ,    4, RX      ),    // UART4_RX
    AF(UART1_RX        ,    2, UART    ,    1, RX      ),    // UART1_RX
    AF(UART1_RTS       ,    8, UART    ,    1, RTS     ),    // UART1_RTS
};
pin_obj_t pin_PC4  = PIN(PC4   , 1,  16, 15, pin_PC4_af, 3);

// PA2
const pin_af_t pin_PA2_af[] = {
    AF(SSI0_CLK        ,    2, SSI     ,    0, CLK     ),    // SSI0_CLK
};
pin_obj_t pin_PA2  = PIN(PA2   , 1,   4, 18, pin_PA2_af, 1);

// PA3
const pin_af_t pin_PA3_af[] = {
    AF(SSI0_FSS        ,    2, SSI     ,    0, FSS     ),    // SSI0_FSS
};
pin_obj_t pin_PA3  = PIN(PA3   , 1,   8, 19, pin_PA3_af, 1);

// PA4
const pin_af_t pin_PA4_af[] = {
    AF(SSI0_RX         ,    2, SSI     ,    0, RX      ),    // SSI0_RX
};
pin_obj_t pin_PA4  = PIN(PA4   , 1,  16, 20, pin_PA4_af, 1);

// PA5
const pin_af_t pin_PA5_af[] = {
    AF(SSI0_TX         ,    2, SSI     ,    0, TX      ),    // SSI0_TX
};
pin_obj_t pin_PA5  = PIN(PA5   , 1,  32, 21, pin_PA5_af, 1);

// PA6
const pin_af_t pin_PA6_af[] = {
    AF(I2C1_SCL        ,    3, I2C     ,    1, SCL     ),    // I2C1_SCL
};
pin_obj_t pin_PA6  = PIN(PA6   , 1,  64, 22, pin_PA6_af, 1);

// PA7
const pin_af_t pin_PA7_af[] = {
    AF(I2C1_SDA        ,    3, I2C     ,    1, SDA     ),    // I2C1_SDA
};
pin_obj_t pin_PA7  = PIN(PA7   , 1, 128, 23, pin_PA7_af, 1);

// PF0
const pin_af_t pin_PF0_af[] = {
    AF(UART1_RTS       ,    1, UART    ,    1, RTS     ),    // UART1_RTS
    AF(SSI1_RX         ,    2, SSI     ,    1, RX      ),    // SSI1_RX
};
pin_obj_t pin_PF0  = PIN(PF0   , 1,   1, 27, pin_PF0_af, 2);

// PF1
const pin_af_t pin_PF1_af[] = {
    AF(UART1_CTS       ,    1, UART    ,    1, CTS     ),    // UART1_CTS
    AF(SSI1_TX         ,    2, SSI     ,    1, TX      ),    // SSI1_TX
};
pin_obj_t pin_PF1  = PIN(PF1   , 1,   2, 28, pin_PF1_af, 2);

// PF2
const pin_af_t pin_PF2_af[] = {
    AF(SSI1_CLK        ,    2, SSI     ,    1, CLK     ),    // SSI1_CLK
};
pin_obj_t pin_PF2  = PIN(PF2   , 1,   4, 29, pin_PF2_af, 1);

// PF3
const pin_af_t pin_PF3_af[] = {
    AF(SSI1_FSS        ,    2, SSI     ,    1, FSS     ),    // SSI1_FSS
};
pin_obj_t pin_PF3  = PIN(PF3   , 1,   8, 30, pin_PF3_af, 1);

// PB0
const pin_af_t pin_PB0_af[] = {
    AF(UART1_RX        ,    1, UART    ,    1, RX      ),    // UART1_RX
};
pin_obj_t pin_PB0  = PIN(PB0   , 1,   1, 44, pin_PB0_af, 1);

// PB1
const pin_af_t pin_PB1_af[] = {
    AF(UART1_TX        ,    1, UART    ,    1, TX      ),    // UART1_TX
};
pin_obj_t pin_PB1  = PIN(PB1   , 1,   2, 45, pin_PB1_af, 1);

// PB2
const pin_af_t pin_PB2_af[] = {
    AF(I2C0_SCL        ,    3, I2C     ,    0, SCL     ),    // I2C0_SCL
};
pin_obj_t pin_PB2  = PIN(PB2   , 1,   4, 46, pin_PB2_af, 1);

// PB3
const pin_af_t pin_PB3_af[] = {
    AF(I2C0_SDA        ,    3, I2C     ,    0, SDA     ),    // I2C0_SDA
};
pin_obj_t pin_PB3  = PIN(PB3   , 1,   8, 47, pin_PB3_af, 1);

// PD6
const pin_af_t pin_PD6_af[] = {
    AF(UART2_RX        ,    1, UART    ,    2, RX      ),    // UART2_RX
};
pin_obj_t pin_PD6  = PIN(PD6   , 1,  64, 52, pin_PD6_af, 1);

// PB5
pin_obj_t pin_PB5  = PIN(PB5   , 1,  32, 56, NULL, 0);

// PB4
const pin_af_t pin_PB4_af[] = {
    AF(SSI2_CLK        ,    1, SSI     ,    2, CLK     ),    // SSI2_CLK
};
pin_obj_t pin_PB4  = PIN(PB4   , 1,  16, 57, pin_PB4_af, 1);

// PE4
const pin_af_t pin_PE4_af[] = {
    AF(UART5_RX        ,    1, UART    ,    5, RX      ),    // UART5_RX
    AF(I2C2_SCL        ,    3, I2C     ,    2, SCL     ),    // I2C2_SCL
};
pin_obj_t pin_PE4  = PIN(PE4   , 1,  16, 58, pin_PE4_af, 2);

// PE5
const pin_af_t pin_PE5_af[] = {
    AF(UART5_TX        ,    1, UART    ,    5, TX      ),    // UART5_TX
    AF(I2C2_SDA        ,    3, I2C     ,    2, SDA     ),    // I2C2_SDA
};
pin_obj_t pin_PE5  = PIN(PE5   , 1,  32, 59, pin_PE5_af, 2);

// PD0
const pin_af_t pin_PD0_af[] = {
    AF(SSI3_CLK        ,    1, SSI     ,    3, CLK     ),    // SSI3_CLK
    AF(SSI1_CLK        ,    2, SSI     ,    1, CLK     ),    // SSI1_CLK
    AF(I2C3_SCL        ,    3, I2C     ,    3, SCL     ),    // I2C3_SCL
};
pin_obj_t pin_PD0  = PIN(PD0   , 1,   1, 60, pin_PD0_af, 3);

// PD1
const pin_af_t pin_PD1_af[] = {
    AF(SSI3_FSS        ,    1, SSI     ,    3, FSS     ),    // SSI3_FSS
    AF(SSI1_FSS        ,    2, SSI     ,    1, FSS     ),    // SSI1_FSS
    AF(I2C3_SDA        ,    3, I2C     ,    3, SDA     ),    // I2C3_SDA
};
pin_obj_t pin_PD1  = PIN(PD1   , 1,   2, 61, pin_PD1_af, 3);

// PD2
const pin_af_t pin_PD2_af[] = {
    AF(SSI3_RX         ,    1, SSI     ,    3, RX      ),    // SSI3_RX
    AF(SSI1_RX         ,    2, SSI     ,    1, RX      ),    // SSI1_RX
};
pin_obj_t pin_PD2  = PIN(PD2   , 1,   4, 62, pin_PD2_af, 2);

// PD3
const pin_af_t pin_PD3_af[] = {
    AF(SSI3_TX         ,    1, SSI     ,    3, TX      ),    // SSI3_TX
    AF(SSI1_TX         ,    2, SSI     ,    1, TX      ),    // SSI1_TX
};
pin_obj_t pin_PD3  = PIN(PD3   , 1,   8, 63, pin_PD3_af, 2);


STATIC const mp_map_elem_t pin_board_pins_locals_dict_table[] = {
    { MP_OBJ_NEW_QSTR(MP_QSTR_PB6   ), (mp_obj_t)&pin_PB6    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PB7   ), (mp_obj_t)&pin_PB7    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PF4   ), (mp_obj_t)&pin_PF4    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PE3   ), (mp_obj_t)&pin_PE3    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PE2   ), (mp_obj_t)&pin_PE2    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PE1   ), (mp_obj_t)&pin_PE1    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PE0   ), (mp_obj_t)&pin_PE0    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PD7   ), (mp_obj_t)&pin_PD7    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PC7   ), (mp_obj_t)&pin_PC7    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PC6   ), (mp_obj_t)&pin_PC6    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PC5   ), (mp_obj_t)&pin_PC5    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PC4   ), (mp_obj_t)&pin_PC4    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PA2   ), (mp_obj_t)&pin_PA2    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PA3   ), (mp_obj_t)&pin_PA3    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PA4   ), (mp_obj_t)&pin_PA4    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PA5   ), (mp_obj_t)&pin_PA5    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PA6   ), (mp_obj_t)&pin_PA6    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PA7   ), (mp_obj_t)&pin_PA7    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PF0   ), (mp_obj_t)&pin_PF0    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PF1   ), (mp_obj_t)&pin_PF1    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PF2   ), (mp_obj_t)&pin_PF2    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PF3   ), (mp_obj_t)&pin_PF3    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PB0   ), (mp_obj_t)&pin_PB0    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PB1   ), (mp_obj_t)&pin_PB1    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PB2   ), (mp_obj_t)&pin_PB2    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PB3   ), (mp_obj_t)&pin_PB3    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PD6   ), (mp_obj_t)&pin_PD6    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PB5   ), (mp_obj_t)&pin_PB5    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PB4   ), (mp_obj_t)&pin_PB4    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PE4   ), (mp_obj_t)&pin_PE4    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PE5   ), (mp_obj_t)&pin_PE5    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PD0   ), (mp_obj_t)&pin_PD0    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PD1   ), (mp_obj_t)&pin_PD1    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PD2   ), (mp_obj_t)&pin_PD2    },
    { MP_OBJ_NEW_QSTR(MP_QSTR_PD3   ), (mp_obj_t)&pin_PD3    },
};
MP_DEFINE_CONST_DICT(pin_board_pins_locals_dict, pin_board_pins_locals_dict_table);

